language: node_js
node_js:
- 5.9
- 5
sudo: required
install:
- sh -c ./build/jdk8-install.sh
- sh -c ./build/gremlin-server/install.sh
- npm install
- npm --prefix ./node_modules/gremlin run build
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm run build
script: npm run test:coverage
env:
  global:
  - GREMLINSERVER_VERSION="3.1.1"
